---
title: Scripting is Life
timezone: UTC
collections:
  posts:
    output: true
  uploads:
    output: true
name: Scripting is Life
description: The journey of a security professional with too many projects.
avatar: "/images/profile.png"
paginate: 5
footer-links:
  dribbble: 
  email: nathaniel@scriptingis.life
  facebook: 
  flickr: 
  github: scriptingislife
  instagram: 
  linkedin: nathaniel-beckstead
  pinterest: 
  rss: becksteadn
  twitter: scriptingislife
  stackoverflow: 
  youtube: 
  googleplus: 
disqus:
#disqus: becksteadn-blog.disqus.com
google_analytics: UA-90662247-1
url: https://scriptingis.life
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
